### ISSUE TITLE
Cannot export mmsegmentation model to ONNX or TensorRT

### ISSUE THREAD

**Issue by jonGuti13** [OpenGVLab/InternImage#234]
I want to export a mmsegmentation model from PyTorch to Tensorflow, but I think I need an intermediate representation such as ONNX/TensorRT. A user asked about this in https://github.com/OpenGVLab/InternImage/issues/61 and the response was to use the script found [here](https://github.com/OpenGVLab/InternImage/tree/master/segmentation#export).

These are the steps I have followed:
First, I have created a Docker container which contains the internimage conda environment which has been created following the steps in https://github.com/OpenGVLab/InternImage/tree/master/segmentation#install

The list of packages installed inside that environment and their corresponding versions are the following ones:
```
#Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
addict                    2.4.0                    pypi_0    pypi
aliyun-python-sdk-core    2.13.36                  pypi_0    pypi
aliyun-python-sdk-kms     2.16.1                   pypi_0    pypi
blas                      1.0                         mkl
brotlipy                  0.7.0           py37h27cfd23_1003
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2023.7.22            hbcca054_0    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py37h5eee18b_3
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.1.7                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
crcmod                    1.7                      pypi_0    pypi
cryptography              39.0.1           py37h9ce1e76_0
cudatoolkit               11.3.1               h2bc3f7f_2
cycler                    0.11.0                   pypi_0    pypi
dcnv3                     1.0                      pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.12.2                   pypi_0    pypi
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.12.1               h4a9f257_0
fsspec                    2023.1.0                 pypi_0    pypi
giflib                    5.2.1                h5eee18b_3
gmp                       6.2.1                h295c915_3
gnutls                    3.6.15               he1e5248_0
huggingface-hub           0.16.4                   pypi_0    pypi
idna                      3.4              py37h06a4308_0
importlib-metadata        6.7.0                    pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561
jmespath                  0.10.0                   pypi_0    pypi
jpeg                      9e                   h5eee18b_1
kiwisolver                1.4.5                    pypi_0    pypi
lame                      3.100                h7b6447c_0
lcms2                     2.12                 h3be6417_0
ld_impl_linux-64          2.38                 h1181459_1
lerc                      3.0                  h295c915_0
libblas                   3.9.0            12_linux64_mkl    conda-forge
libcblas                  3.9.0            12_linux64_mkl    conda-forge
libdeflate                1.17                 h5eee18b_0
libffi                    3.4.4                h6a678d5_0
libgcc-ng                 11.2.0               h1234567_1
libgfortran-ng            13.1.0               h69a702a_0    conda-forge
libgfortran5              13.1.0               h15d22d2_0    conda-forge
libgomp                   11.2.0               h1234567_1
libiconv                  1.16                 h7f8727e_2
libidn2                   2.3.4                h5eee18b_0
liblapack                 3.9.0            12_linux64_mkl    conda-forge
libpng                    1.6.39               h5eee18b_0
libstdcxx-ng              11.2.0               h1234567_1
libtasn1                  4.19.0               h5eee18b_0
libtiff                   4.5.1                h6a678d5_0
libunistring              0.9.10               h27cfd23_0
libuv                     1.44.2               h5eee18b_0
libwebp                   1.2.4                h11a3e52_1
libwebp-base              1.2.4                h5eee18b_1
lz4-c                     1.9.4                h6a678d5_0
markdown                  3.4.4                    pypi_0    pypi
markdown-it-py            2.2.0                    pypi_0    pypi
matplotlib                3.5.3                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640
mkl-service               2.4.0            py37h7f8727e_0
mkl_fft                   1.3.1            py37hd3c417c_0
mkl_random                1.2.2            py37h51133e4_0
mmcls                     0.25.0                   pypi_0    pypi
mmcv-full                 1.5.0                    pypi_0    pypi
mmdet                     2.28.1                   pypi_0    pypi
mmsegmentation            0.27.0                   pypi_0    pypi
model-index               0.1.11                   pypi_0    pypi
ncurses                   6.4                  h6a678d5_0
nettle                    3.7.3                hbbd107a_1
numpy                     1.21.5           py37h6c91a56_3
numpy-base                1.21.5           py37ha15fc14_3
opencv-python             4.8.0.76                 pypi_0    pypi
opendatalab               0.0.10                   pypi_0    pypi
openh264                  2.1.1                h4ff587b_0
openmim                   0.3.9                    pypi_0    pypi
openssl                   1.1.1v               h7f8727e_0
openxlab                  0.0.10                   pypi_0    pypi
ordered-set               4.1.0                    pypi_0    pypi
oss2                      2.17.0                   pypi_0    pypi
packaging                 23.1                     pypi_0    pypi
pandas                    1.3.5                    pypi_0    pypi
pillow                    9.4.0            py37h6a678d5_0
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
platformdirs              3.10.0                   pypi_0    pypi
prettytable               3.7.0                    pypi_0    pypi
pycocotools               2.0.7                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0
pycryptodome              3.18.0                   pypi_0    pypi
pygments                  2.16.1                   pypi_0    pypi
pyopenssl                 23.0.0           py37h06a4308_0
pyparsing                 3.1.1                    pypi_0    pypi
pysocks                   1.7.1                    py37_1
python                    3.7.16               h7a1cb2a_0
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.7                     2_cp37m    conda-forge
pytorch                   1.11.0          py3.7_cuda11.3_cudnn8.2.0_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2023.3.post1             pypi_0    pypi
pyyaml                    6.0              py37h540881e_4    conda-forge
readline                  8.2                  h5eee18b_0
requests                  2.28.2                   pypi_0    pypi
rich                      13.5.2                   pypi_0    pypi
scipy                     1.7.3            py37hf2a6cf1_0    conda-forge
setuptools                60.2.0                   pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1
sqlite                    3.41.2               h5eee18b_0
tabulate                  0.9.0                    pypi_0    pypi
termcolor                 2.3.0              pyhd8ed1ab_0    conda-forge
terminaltables            3.1.10                   pypi_0    pypi
timm                      0.6.11                   pypi_0    pypi
tk                        8.6.12               h1ccaba5_0
tomli                     2.0.1                    pypi_0    pypi
torchaudio                0.11.0               py37_cu113    pytorch
torchvision               0.12.0               py37_cu113    pytorch
tqdm                      4.65.2                   pypi_0    pypi
typing-extensions         4.7.1                    pypi_0    pypi
urllib3                   1.26.14          py37h06a4308_0
wcwidth                   0.2.6                    pypi_0    pypi
wheel                     0.38.4           py37h06a4308_0
xz                        5.4.2                h5eee18b_0
yacs                      0.1.8              pyhd8ed1ab_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yapf                      0.40.1                   pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0
zstd                      1.5.5                hc292b87_0
```
When running
```
python deploy.py "./deploy/configs/mmseg/segmentation_tensorrt_static-512x512.py" \
    "./configs/ade20k/upernet_internimage_t_512_160k_ade20k.py" \
    "checkpoint_dir/seg/upernet_internimage_t_512_160k_ade20k.pth" \
    "./deploy/demo.png" \
    --work-dir "./work_dirs/mmseg/upernet_internimage_t_512_160k_ade20k" \
    --device cuda
    --dump-info
```
I get the following error `No module named ‘mmdeploy’` (I name this error as ERROR 1.0).
To solve it, I have read the documentation from https://mmdeploy.readthedocs.io/en/latest/get_started.html
Differently from me, they create an environment with Python 3.8 (mine is 3.7 and the prerequisite is Python3.6+) and install some packages with the following specific commands:
```
pip install -U openmim
mim install mmengine
mim install "mmcv>=2.0.0rc2"    #I will mention this in the conclusions

# 1. install MMDeploy model converter
pip install mmdeploy==1.2.0
```
At this point the versions of the packages which are related to MMCV are
```
mmcls                     0.25.0                   pypi_0    pypi
mmcv                      2.0.1                    pypi_0    pypi
mmcv-full                 1.5.0                    pypi_0    pypi
mmdeploy                  1.2.0                    pypi_0    pypi
mmdet                     2.28.1                   pypi_0    pypi
mmengine                  0.8.4                    pypi_0    pypi
mmsegmentation            0.27.0                   pypi_0    pypi
```

I run again the `python deploy.py ... ` command and get the error `cannot import name 'print_log' from 'mmcv'` (ERROR 2.0)
```
File "deploy.py", line 22, in <module>
    import mmcv_custom
  File "/workspace/InternImage/segmentation/mmcv_custom/__init__.py", line 8, in <module>
    from .custom_layer_decay_optimizer_constructor import CustomLayerDecayOptimizerConstructor
  File "/workspace/InternImage/segmentation/mmcv_custom/custom_layer_decay_optimizer_constructor.py", line 13, in <module>
    from mmcv.runner import OPTIMIZER_BUILDERS, DefaultOptimizerConstructor
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmcv/runner/__init__.py", line 3, in <module>
    from .base_runner import BaseRunner
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 12, in <module>
    from ..parallel import is_module_wrapper
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmcv/parallel/__init__.py", line 5, in <module>
    from .distributed import MMDistributedDataParallel
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 6, in <module>
    from mmcv import print_log
ImportError: cannot import name 'print_log' from 'mmcv' (/opt/conda/envs/internimage/lib/python3.7/site-packages/mmcv/__init__.py)
```
There is (https://github.com/OpenGVLab/InternImage/issues/91) long issue speaking about that problem and although there are some possible workarounds, none of them work for me.

Aptly, a user suggests changing line 6 in `distributed.py` because for `mmcv=>2.0.0` `"print_log"` function is implemented in `"mmengine"`. So instead of `from mmcv import print_log`, I write `from mmengine import print_log`. However, as other users also report, there is still another error `ImportError: cannot import name 'TORCH_VERSION' from 'mmcv.utils' `(ERROR 3.0)
```
Traceback (most recent call last):
  File "deploy.py", line 22, in <module>
    import mmcv_custom
  File "/workspace/InternImage/segmentation/mmcv_custom/__init__.py", line 8, in <module>
    from .custom_layer_decay_optimizer_constructor import CustomLayerDecayOptimizerConstructor
  File "/workspace/InternImage/segmentation/mmcv_custom/custom_layer_decay_optimizer_constructor.py", line 13, in <module>
    from mmcv.runner import OPTIMIZER_BUILDERS, DefaultOptimizerConstructor
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmcv/runner/__init__.py", line 3, in <module>
    from .base_runner import BaseRunner
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 12, in <module>
    from ..parallel import is_module_wrapper
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmcv/parallel/__init__.py", line 5, in <module>
    from .distributed import MMDistributedDataParallel
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 7, in <module>
    from mmcv.utils import TORCH_VERSION, digit_version
ImportError: cannot import name 'TORCH_VERSION' from 'mmcv.utils' (/opt/conda/envs/internimage/lib/python3.7/site-packages/mmcv/utils/__init__.py)
```
In the same issue, a user states that the problem was solved by downgrading to `mmcv-full==1.5.0` and mim installing the corresponding version of `mmsegmentation==0.27.0` . The user explains that the solution was figured out after taking a look at mmcv, because it looks like there was a change in `mmcv.utils.init` between version 1.x (which is expected by InternImage) and version 2.x.
The user adds that `mmsegmentation` is missing from InternImage installation instructions but that has been corrected https://github.com/OpenGVLab/InternImage/tree/master/segmentation

```
mim uninstall mmcv mmcv-full
mim install mmcv-full==1.5.0
mim install mmsegmentation==0.27.0
```

As far as I know, those commands leave the environment as it was at the beginning, that is, with `mmcv-full` and no `mmcv` (I will mention this in the conclusions) except for that `mmdeploy` has been installed.
So instead of getting the ERROR 1.0, I get a different one  (I have installed mmdeploy) `ImportError: cannot import name 'register_all_modules' from 'mmseg.utils.set_env'` (ERROR 2.1)

```
Traceback (most recent call last):
  File "deploy.py", line 310, in <module>
    main()
  File "deploy.py", line 136, in main
    device=args.device)
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmdeploy/backend/sdk/export_info.py", line 352, in export2SDK
    deploy_info = get_deploy(deploy_cfg, model_cfg, work_dir, device)
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmdeploy/backend/sdk/export_info.py", line 268, in get_deploy
    deploy_cfg, model_cfg, work_dir=work_dir, device=device)
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmdeploy/backend/sdk/export_info.py", line 62, in get_model_name_customs
    model_cfg=model_cfg, deploy_cfg=deploy_cfg, device=device)
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmdeploy/apis/utils/utils.py", line 46, in build_task_processor
    import_codebase(codebase_type, custom_module_list)
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmdeploy/codebase/__init__.py", line 37, in import_codebase
    codebase.register_all_modules()
  File "/opt/conda/envs/internimage/lib/python3.7/site-packages/mmdeploy/codebase/mmseg/deploy/segmentation.py", line 116, in register_all_modules
    from mmseg.utils.set_env import register_all_modules
ImportError: cannot import name 'register_all_modules' from 'mmseg.utils.set_env' (/opt/conda/envs/internimage/lib/python3.7/site-packages/mmseg/utils/set_env.py)
```
This error is very similar (except for that the user is attempting detection and I am attempting segmentation) to the ones reported in https://github.com/OpenGVLab/InternImage/issues/110 and also in https://github.com/OpenGVLab/InternImage/issues/102 which are still unresolved.

At this point, the versions of the packages related to MMCV are:
```
mmcls                     0.25.0                   pypi_0    pypi
mmcv-full                 1.5.0                    pypi_0    pypi
mmdeploy                  1.2.0                    pypi_0    pypi
mmdet                     2.28.1                   pypi_0    pypi
mmengine                  0.8.4                    pypi_0    pypi
mmsegmentation            0.27.0                   pypi_0    pypi
```
My own conclusions until now are:
- If I haven't mistakenly omitted any step in the internimage installation guidelines, `mmcv` is not installed so I don't know if it is necessary.

- However, when installing mmdeploy you are said to install "mmcv>=2.0.0rc2". With that `mmcv` version, there is neither `'print_log'`(can be solved) in `mmcv/__init__.py` nor `'TORCH_VERSION'` in `mmcv/utils/__init__.py` (can't be solved)

- If you install an older version of `mmcv` such as 1.5.3, I have verified that both `'print_log'` and `'TORCH_VERSION'` work/exist, but another error appears `ImportError: cannot import name 'register_all_modules' from 'mmseg.utils.set_env'` (can't be solved). This last error is very similar to the one described in https://github.com/open-mmlab/mmdeploy/issues/1480 and it seems that it is a version related issue but it worked out well with Windows. As I haven't change the `mmsegmentation` version, I hope that `mmcv` related problems have been solved and it is only `'mmseg'` related ones. However, if I install a higher version of mmseg (1.X),
automatically mmcv is updated to `mmcv==2.X` which is what I don't want.

- The fact that it may be a version related problem gains strength when you read https://mmcv.readthedocs.io/en/latest/compatibility.html but I still can't solve my problem.
When I have been using `MMCV < 2.0` I have used `mmcv-full` or `mmcv < 2.0.0`.

Can someone please shed light on this issue or propose a different way of converting a MMCV model to ONNX/Tensorflow/TensorRT? Thanks in advance.

**Comment by George0726** [comment]
I confront the same issue

**Comment by bojanb98** [comment]
I had the same issue, but it was solved by using mmdeploy v0.14.0

**Comment by jonGuti13** [comment]
@bojanb98 I ended up learning how to train/test models with openmmlab, but thank you for your response.

**Comment by julian-zaya** [comment]
same issue

**Comment by jonGuti13** [comment]
> @jonGuti13 have you achieve the convert of segmentation model? if you got it please contact with me!

Hi @GitHubYuxiao,
No, I ended up learning how to train/test models with mmsegmentation, sorry.

**Comment by GitHubYuxiao** [comment]
> > @jonGuti13 have you achieve the convert of segmentation model? if you got it please contact with me!
> 
> Hi @GitHubYuxiao, No, I ended up learning how to train/test models with mmsegmentation, sorry.

ok  thank you reply
