### ISSUE TITLE
error in dcnv3_col2im_cuda: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by zhangch-ss** [OpenGVLab/InternImage#93]
What is the reason

**Comment by 116022017144** [comment]
I met this error, the enviroment maybe has some problem.

**Comment by quocthinhvo** [comment]
I encountered a similar issue on an RTX 2080ti card with CUDA 12.0. Here's how I fixed it.

- Use the docker image: pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel
- Install the packages as instructed. However, when it comes to compiling CUDA operators build from source, you will be able to fix the error.
